version: '3.9'
services:
  mysqlService:
    image: mysql:latest
    container_name: mysql
    networks:
      - kanban-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  user-service:
    image: userimage
    container_name: usercontainer
    build: UserService/
    restart: always
    networks:
      - kanban-network
    ports:
      - "8081:8081"
    depends_on:
      - mysqlService
      - api-gateway

  kanban-service:
    image: kanbanimage
    container_name: kanban-container
    build: KanbanService/
    restart: always
    networks:
      - kanban-network
    ports:
      - "8082:8082"
    depends_on:
      - mongoService
      - rabbitmqService
      - api-gateway


  mongoService:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - kanban-network

  notification-service:
    image: notificationimage
    container_name: notification-container
    build: NotificationService/
    restart: always
    networks:
      - kanban-network
    ports:
      - "8083:8083"
    depends_on:
      - mongoService
      - rabbitmqService
      - api-gateway

  rabbitmqService:
    image: rabbitmq:management
    container_name: rabbitmq-container
    ports:
      - "5672:15672"
      - "15672:15672"
    networks:
      - kanban-network
    restart: always

  api-gateway:
    container_name: api-gateway
    build: ApiGatewayService/
    restart: always
    networks:
      - kanban-network
    ports:
      - "9005:9005"

  eurekaservice:
    container_name: spring-cloud-eureka
    build: EurekaService/
    restart: always
    networks:
      - kanban-network
    ports:
      - "8761:8761"


networks:
  kanban-network:
    name: kanban-network
    driver: bridge
